from django.urls import path

from .views import (
    AttendanceActivityView,
    MyAttendanceDetailView,
    AttendanceScanView,
    AttendanceRegisterView,
    GenerateCredentialsView,
    LoginView,
    MyCoursesView,
    MyAttendanceListView,
    ProfessorStudentEnrollmentDetailView,
    ProfessorAssignCourseView,
    ProfessorCourseDetailView,
    ProfessorDetailView,
    ProfessorStudentsListView,
    ProfessorStudentRegisterView,
    ProfessorCreateListView,
    ProfessorAttendanceEventsView,
    ProfessorAttendanceEventDetailView,
    ProfessorDailyEventsReportView,
    SchoolInfoView,
    ShiftConfigListCreateView,
    ShiftConfigDetailView,
    StudentDetailView,
    StudentRegisterListView,
)

urlpatterns = [
    path('school-info/', SchoolInfoView.as_view(), name='school-info'),
    path('auth/login/', LoginView.as_view(), name='login'),
    path('professor/my-courses/', MyCoursesView.as_view(), name='professor-my-courses'),
    path('professor/my-events/', ProfessorAttendanceEventsView.as_view(), name='professor-my-events'),
    path('professor/my-events/<int:event_id>/', ProfessorAttendanceEventDetailView.as_view(), name='professor-my-events-detail'),
    path('professor/daily-report/', ProfessorDailyEventsReportView.as_view(), name='professor-daily-report'),
    path('professor/students/', ProfessorStudentsListView.as_view(), name='professor-students-list'),
    path('professor/students/enrollment/<int:enrollment_id>/', ProfessorStudentEnrollmentDetailView.as_view(), name='professor-student-enrollment-detail'),
    path('professor/students/register/', ProfessorStudentRegisterView.as_view(), name='professor-students-register'),
    path('professors/', ProfessorCreateListView.as_view(), name='professors'),
    path('professors/<int:professor_id>/', ProfessorDetailView.as_view(), name='professor-detail'),
    path('professors/<int:professor_id>/courses/', ProfessorAssignCourseView.as_view(), name='professor-assign-course'),
    path('professors/<int:professor_id>/courses/<int:course_id>/', ProfessorCourseDetailView.as_view(), name='professor-course-detail'),
    path('students/', StudentRegisterListView.as_view(), name='students'),
    path('students/<int:student_id>/', StudentDetailView.as_view(), name='student-detail'),
    path('attendance/scan/', AttendanceScanView.as_view(), name='attendance-scan'),
    path('attendance/register/', AttendanceRegisterView.as_view(), name='attendance-register'),
    path('attendance/mine/', MyAttendanceListView.as_view(), name='attendance-mine'),
    path('attendance/activity/', AttendanceActivityView.as_view(), name='attendance-activity'),
    path('attendance/mine/<int:attendance_id>/', MyAttendanceDetailView.as_view(), name='attendance-mine-detail'),
    path('credentials/generate/', GenerateCredentialsView.as_view(), name='generate-credentials'),
    path('shift-configs/', ShiftConfigListCreateView.as_view(), name='shift-configs'),
    path('shift-configs/<int:shift_id>/', ShiftConfigDetailView.as_view(), name='shift-config-detail'),
]
