# Generated by Django 5.2.12 on 2026-03-09 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_studentprofile_ci_studentprofile_course_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRAttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('ci', models.CharField(max_length=20)),
                ('student_name', models.CharField(max_length=200)),
                ('course_name', models.CharField(max_length=120)),
                ('raw_payload', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_attendances', to='core.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'date')},
            },
        ),
    ]
