# Generated by Django 5.2.12 on 2026-03-09 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_qrattendancerecord'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='qrattendancerecord',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='qrattendancerecord',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_attendances', to='core.course'),
        ),
        migrations.AlterUniqueTogether(
            name='qrattendancerecord',
            unique_together={('student', 'course', 'date')},
        ),
    ]
