# Generated by Django 5.2.12 on 2026-03-09 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_qrattendancerecord_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('present_until', models.TimeField()),
                ('late_until', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_events', to='core.course')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_events', to='core.professorprofile')),
            ],
            options={
                'ordering': ('-date', '-start_time', '-id'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendance',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.attendanceevent'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'event')},
        ),
    ]
