# Generated by Django 5.2.11 on 2026-03-12 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_enrollment_single_course'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='qrattendancerecord',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='qrattendancerecord',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_attendances', to='core.attendanceevent'),
        ),
        migrations.AddConstraint(
            model_name='qrattendancerecord',
            constraint=models.UniqueConstraint(fields=('student', 'event'), name='uq_qr_student_event'),
        ),
        migrations.AddConstraint(
            model_name='qrattendancerecord',
            constraint=models.UniqueConstraint(condition=models.Q(('event__isnull', True)), fields=('student', 'course', 'date'), name='uq_qr_student_course_date_no_event'),
        ),
    ]
