# Generated by Django 5.2.12 on 2026-03-18 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_qrattendancerecord_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='scanned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
