# Generated by Django 5.2.11 on 2026-03-25 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_attendance_scanned_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_type', models.CharField(choices=[('MORNING', 'Mañana'), ('AFTERNOON', 'Tarde')], max_length=20, unique=True, verbose_name='Turno')),
                ('start_time', models.TimeField(help_text='Hora en que inicia el turno', verbose_name='Hora de inicio')),
                ('tolerance_minutes', models.IntegerField(default=10, help_text='Minutos después del inicio para marcar como PRESENTE', verbose_name='Tolerancia para presente (minutos)')),
                ('late_minutes', models.IntegerField(default=20, help_text='Minutos después del inicio para marcar como TARDE (después de esto se marca AUSENTE)', verbose_name='Tolerancia para tarde (minutos)')),
                ('is_active', models.BooleanField(default=True, help_text='Si está activo, los profesores pueden usar este turno', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Turno',
                'verbose_name_plural': 'Configuración de Turnos',
                'ordering': ['shift_type'],
            },
        ),
    ]
