# Generated by Django 5.2.11 on 2026-03-26 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_shiftconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='core.shiftconfig', verbose_name='Turno/Periodo'),
        ),
        migrations.AddField(
            model_name='attendanceevent',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_events', to='core.shiftconfig', verbose_name='Turno/Periodo'),
        ),
    ]
