# Generated by Django 5.2.11 on 2026-03-26 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_attendance_shift_attendanceevent_shift'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendanceevent',
            options={'ordering': ('-date', '-id')},
        ),
        migrations.RemoveField(
            model_name='attendanceevent',
            name='late_until',
        ),
        migrations.RemoveField(
            model_name='attendanceevent',
            name='present_until',
        ),
        migrations.RemoveField(
            model_name='attendanceevent',
            name='start_time',
        ),
    ]
