# Generated by Django 5.2.11 on 2026-03-27 20:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_time_fields_from_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceevent',
            name='start_time',
            field=models.TimeField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='attendanceevent',
            name='present_until',
            field=models.TimeField(null=True, blank=True, help_text='Hora límite para marcar como presente'),
        ),
        migrations.AddField(
            model_name='attendanceevent',
            name='late_until',
            field=models.TimeField(null=True, blank=True, help_text='Hora límite para marcar como tarde'),
        ),
        migrations.AddField(
            model_name='attendanceevent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='attendanceevent',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='attendanceevent',
            name='date',
            field=models.DateField(null=True, blank=True),
        ),
    ]

