# Generated by Django 5.2.11 on 2026-03-27 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_restore_event_time_fields'),
    ]

    operations = [
    ]
