# Generated by Django 5.2.11 on 2026-03-27 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_fix_model_schema'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendanceevent',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='qrattendancerecord',
            name='uq_qr_student_event',
        ),
        migrations.RemoveConstraint(
            model_name='qrattendancerecord',
            name='uq_qr_student_course_date_no_event',
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'course', 'shift', 'date')},
        ),
        migrations.RemoveField(
            model_name='attendanceevent',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='qrattendancerecord',
            name='event',
        ),
        migrations.AddField(
            model_name='qrattendancerecord',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_attendance_records', to='core.shiftconfig'),
        ),
        migrations.AlterField(
            model_name='qrattendancerecord',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_attendances', to='core.course'),
        ),
        migrations.AddConstraint(
            model_name='qrattendancerecord',
            constraint=models.UniqueConstraint(fields=('student', 'course', 'shift', 'date'), name='uq_qr_student_course_shift_date'),
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='event',
        ),
    ]
