# Generated by Django 5.2.11 on 2026-03-27 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_attendanceevent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceevent',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Si el evento está activo para registrar asistencia'),
        ),
    ]
